# Generated by Django 5.2.14 on 2026-05-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteIdentity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_kabupaten",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Nama Kabupaten",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Identitas Situs",
                "verbose_name_plural": "Identitas Situs",
            },
        ),
    ]
