# Generated by Django 5.2.14 on 2026-05-25 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomor_reg",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Nomor Reg"
                    ),
                ),
                ("user_label", models.CharField(default="Publik", max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("area_ha", models.FloatField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="screening_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Screening Log",
                "verbose_name_plural": "Screening Logs",
                "ordering": ["-created"],
            },
        ),
    ]
