# Generated by Django 5.2.14 on 2026-05-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0002_screeninglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("WIB", "WIB — Waktu Indonesia Barat (UTC+7)"),
                    ("WITA", "WITA — Waktu Indonesia Tengah (UTC+8)"),
                    ("WIT", "WIT — Waktu Indonesia Timur (UTC+9)"),
                ],
                default="WIB",
                max_length=8,
                verbose_name="Zona waktu",
            ),
        ),
    ]
