# Generated by Django 5.2.14 on 2026-05-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0039_remove_modeltranslation"),
        ("geonode_project", "0003_siteidentity_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAccessSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_public_download",
                    models.BooleanField(
                        default=True, verbose_name="Dapat diunduh publik"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dst_access_setting",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengaturan Akses Dokumen",
                "verbose_name_plural": "Pengaturan Akses Dokumen",
            },
        ),
    ]
