# Generated by Django 5.2.14 on 2026-05-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0004_documentaccesssetting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DocumentAccessSetting",
        ),
    ]
