# Generated by Django 5.2.14 on 2026-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0005_delete_documentaccesssetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingSection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True, verbose_name="Kunci")),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Nama section"),
                ),
                (
                    "anchor",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Anchor (id HTML)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Tampil"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Section Landing",
                "verbose_name_plural": "Section Landing",
                "ordering": ["order", "id"],
            },
        ),
    ]
