# Generated by Django 5.2.14 on 2026-05-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0039_remove_modeltranslation"),
        ("geonode_project", "0007_seed_landing_sections"),
        ("layers", "0046_remove_modeltranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="KomoditasFokus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(max_length=120, verbose_name="Nama komoditas"),
                ),
                (
                    "deskripsi",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                (
                    "gambar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="komoditas/",
                        verbose_name="Gambar/Foto",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="layers.dataset",
                        verbose_name="Peta kesesuaian lahan (Dataset)",
                    ),
                ),
                (
                    "dokumen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                        verbose_name="Literatur komoditi (Dokumen)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fokus Komoditas",
                "verbose_name_plural": "Fokus Komoditas",
                "ordering": ["urutan", "id"],
            },
        ),
    ]
