# Generated by Django 5.2.14 on 2026-05-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0009_seed_komoditas_fokus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementingPartner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=150, verbose_name="Nama mitra")),
                ("logo", models.ImageField(upload_to="partners/", verbose_name="Logo")),
                (
                    "tautan",
                    models.URLField(
                        blank=True, default="", verbose_name="Tautan situs"
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Implementing Partner",
                "verbose_name_plural": "Implementing Partners",
                "ordering": ["urutan", "id"],
            },
        ),
    ]
