# Generated by Django 5.2.14 on 2026-06-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0012_seed_komoditas_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="theme",
            field=models.CharField(
                choices=[
                    ("luwu", "Luwu — Editorial Geospatial"),
                    ("pesisir", "Pesisir — Tropical Coastal"),
                    ("pegunungan", "Pegunungan — Highland Stoic"),
                    ("vulkanik", "Vulkanik — Ash & Ember"),
                    ("rawa", "Rawa — Wetland Marigold"),
                ],
                default="luwu",
                max_length=20,
                verbose_name="Tema CMS",
            ),
        ),
    ]
