# Generated by Django 5.2.14 on 2026-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0013_siteidentity_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteidentity",
            name="theme",
            field=models.CharField(
                choices=[
                    ("luwu", "Luwu — Editorial Geospatial"),
                    ("pesisir", "Pesisir — Tropical Coastal"),
                    ("pegunungan", "Pegunungan — Highland Stoic"),
                    ("vulkanik", "Vulkanik — Ash & Ember"),
                    ("rawa", "Rawa — Wetland Marigold"),
                    ("modern", "Modern — Teal Pemerintahan"),
                    ("pastel", "Pastel — Cerah Lembut"),
                    ("kontras", "Kontras — Bold Cerah"),
                ],
                default="luwu",
                max_length=20,
                verbose_name="Tema CMS",
            ),
        ),
    ]
