# Generated by Django 5.2.14 on 2026-06-04 01:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0030_walidatamembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefWilayahDesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "kode_bps",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode BPS",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nama"
                    ),
                ),
                (
                    "luas_ha",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Luas menurut peraturan (HA)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometri"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Disinkron pada"),
                ),
                (
                    "kode_kec_pum",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Kode PUM Kecamatan"
                    ),
                ),
                (
                    "kode_kab_pum",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode PUM Kabupaten/Kota",
                    ),
                ),
                (
                    "kode_prov_pum",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Kode PUM Provinsi"
                    ),
                ),
                (
                    "nama_kec",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Kecamatan"
                    ),
                ),
                (
                    "nama_kab",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Kabupaten/Kota"
                    ),
                ),
                (
                    "nama_prov",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Provinsi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ref Wilayah — Desa/Kelurahan",
                "verbose_name_plural": "Ref Wilayah — Desa/Kelurahan",
                "ordering": ["kode_pum"],
            },
        ),
        migrations.CreateModel(
            name="RefWilayahKabkota",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "kode_bps",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode BPS",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nama"
                    ),
                ),
                (
                    "luas_ha",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Luas menurut peraturan (HA)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometri"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Disinkron pada"),
                ),
                (
                    "kode_prov_pum",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Kode PUM Provinsi"
                    ),
                ),
                (
                    "nama_prov",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Provinsi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ref Wilayah — Kabupaten/Kota",
                "verbose_name_plural": "Ref Wilayah — Kabupaten/Kota",
                "ordering": ["kode_pum"],
            },
        ),
        migrations.CreateModel(
            name="RefWilayahKecamatan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "kode_bps",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode BPS",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nama"
                    ),
                ),
                (
                    "luas_ha",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Luas menurut peraturan (HA)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometri"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Disinkron pada"),
                ),
                (
                    "kode_kab_pum",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode PUM Kabupaten/Kota",
                    ),
                ),
                (
                    "kode_prov_pum",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Kode PUM Provinsi"
                    ),
                ),
                (
                    "nama_kab",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Kabupaten/Kota"
                    ),
                ),
                (
                    "nama_prov",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Provinsi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ref Wilayah — Kecamatan",
                "verbose_name_plural": "Ref Wilayah — Kecamatan",
                "ordering": ["kode_pum"],
            },
        ),
        migrations.CreateModel(
            name="RefWilayahProvinsi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "kode_bps",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode BPS",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nama"
                    ),
                ),
                (
                    "luas_ha",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Luas menurut peraturan (HA)",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Geometri"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Disinkron pada"),
                ),
            ],
            options={
                "verbose_name": "Ref Wilayah — Provinsi",
                "verbose_name_plural": "Ref Wilayah — Provinsi",
                "ordering": ["kode_pum"],
            },
        ),
    ]
