# Generated by Django 5.2.14 on 2026-06-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0032_wilayah_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="cakupan_kode_kab",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Kode PUM Kabupaten/Kota cakupan",
            ),
        ),
        migrations.AddField(
            model_name="siteidentity",
            name="cakupan_kode_prov",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="Kode PUM Provinsi cakupan",
            ),
        ),
        migrations.AddField(
            model_name="siteidentity",
            name="cakupan_level",
            field=models.CharField(
                blank=True,
                choices=[("provinsi", "Provinsi"), ("kabupaten", "Kabupaten/Kota")],
                default="",
                help_text="provinsi = muat 1 provinsi penuh; kabupaten = muat 1 kabupaten/kota.",
                max_length=12,
                verbose_name="Level cakupan DST",
            ),
        ),
        migrations.AddField(
            model_name="siteidentity",
            name="cakupan_nama_kab",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nama Kabupaten/Kota cakupan",
            ),
        ),
        migrations.AddField(
            model_name="siteidentity",
            name="cakupan_nama_prov",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Nama Provinsi cakupan",
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahdesa",
            name="kode_bps",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Kode BPS"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahdesa",
            name="kode_kab_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Kabupaten/Kota"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahdesa",
            name="kode_kec_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Kecamatan"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahdesa",
            name="kode_prov_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Provinsi"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahdesa",
            name="kode_pum",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Kode PUM/Kemendagri"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkabkota",
            name="kode_bps",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Kode BPS"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkabkota",
            name="kode_prov_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Provinsi"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkabkota",
            name="kode_pum",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Kode PUM/Kemendagri"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkecamatan",
            name="kode_bps",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Kode BPS"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkecamatan",
            name="kode_kab_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Kabupaten/Kota"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkecamatan",
            name="kode_prov_pum",
            field=models.CharField(
                db_index=True, max_length=32, verbose_name="Kode PUM Provinsi"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahkecamatan",
            name="kode_pum",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Kode PUM/Kemendagri"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahprovinsi",
            name="kode_bps",
            field=models.CharField(
                blank=True, db_index=True, max_length=32, verbose_name="Kode BPS"
            ),
        ),
        migrations.AlterField(
            model_name="refwilayahprovinsi",
            name="kode_pum",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Kode PUM/Kemendagri"
            ),
        ),
    ]
