# Generated by Django 5.2.14 on 2026-06-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0033_siteidentity_cakupan_kode_kab_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdmDesa",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode_desa",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        verbose_name="Kode Desa (Kemendagri, tanpa titik)",
                    ),
                ),
                (
                    "kode_prov",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Kode Provinsi"
                    ),
                ),
                (
                    "kode_kab",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Kode Kabupaten/Kota"
                    ),
                ),
                (
                    "kode_kec",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="Kode Kecamatan"
                    ),
                ),
                (
                    "nama_desa",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Desa/Kelurahan"
                    ),
                ),
                (
                    "nama_kec",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Kecamatan"
                    ),
                ),
                (
                    "nama_kab",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Kabupaten/Kota"
                    ),
                ),
                (
                    "nama_prov",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nama Provinsi"
                    ),
                ),
                (
                    "tahun",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Tahun"
                    ),
                ),
                (
                    "iks",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Indeks Ketahanan Sosial"
                    ),
                ),
                (
                    "ike",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Indeks Ketahanan Ekonomi"
                    ),
                ),
                (
                    "ikl",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Indeks Ketahanan Lingkungan",
                    ),
                ),
                (
                    "skor_idm",
                    models.FloatField(blank=True, null=True, verbose_name="Nilai IDM"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=32,
                        verbose_name="Status IDM",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Disinkron pada"),
                ),
            ],
            options={
                "verbose_name": "IDM Desa",
                "verbose_name_plural": "IDM Desa",
                "db_table": 'wilayah"."idm',
                "ordering": ["kode_desa"],
                "unique_together": {("kode_desa", "tahun")},
            },
        ),
    ]
