# Generated by Django 5.2.14 on 2026-06-04 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0034_idmdesa"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolurIndikator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(max_length=20, verbose_name="Kode")),
                (
                    "nama",
                    models.CharField(max_length=200, verbose_name="Nama indikator"),
                ),
                (
                    "pilar",
                    models.CharField(
                        choices=[
                            ("kawasan_lindung", "Kawasan Lindung"),
                            ("restorasi", "Restorasi Lahan"),
                            ("praktik_lestari", "Praktik Lestari"),
                            ("grk", "Mitigasi GRK"),
                            ("penerima_manfaat", "Penerima Manfaat"),
                            ("value_chain", "Rantai Nilai Komoditas"),
                            ("tata_kelola", "Tata Kelola Bentang Lahan"),
                        ],
                        max_length=20,
                        verbose_name="Pilar",
                    ),
                ),
                (
                    "satuan",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Satuan"
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                (
                    "baseline",
                    models.FloatField(blank=True, null=True, verbose_name="Baseline"),
                ),
                (
                    "target",
                    models.FloatField(blank=True, null=True, verbose_name="Target"),
                ),
                (
                    "arah",
                    models.CharField(
                        choices=[
                            ("naik", "Naik = lebih baik"),
                            ("turun", "Turun = lebih baik"),
                        ],
                        default="naik",
                        max_length=6,
                        verbose_name="Arah capaian",
                    ),
                ),
                (
                    "sumber",
                    models.CharField(
                        choices=[
                            ("manual", "Entri manual"),
                            ("auto", "Otomatis (dari data sistem)"),
                        ],
                        default="manual",
                        max_length=6,
                        verbose_name="Sumber nilai",
                    ),
                ),
                (
                    "auto_key",
                    models.SlugField(
                        blank=True,
                        default="",
                        help_text="Diisi hanya bila sumber=auto; pengenal fungsi penghitung di views.",
                        verbose_name="Kunci komputasi auto",
                    ),
                ),
                (
                    "extra",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Catatan tambahan (badge)",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Indikator FOLUR",
                "verbose_name_plural": "Indikator FOLUR",
                "ordering": ["urutan", "id"],
            },
        ),
        migrations.CreateModel(
            name="FolurCapaian",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tahun",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Tahun"
                    ),
                ),
                ("nilai", models.FloatField(verbose_name="Realisasi")),
                (
                    "catatan",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Catatan"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "indikator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capaian",
                        to="geonode_project.folurindikator",
                        verbose_name="Indikator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capaian FOLUR",
                "verbose_name_plural": "Capaian FOLUR",
                "ordering": ["indikator", "-tahun"],
                "unique_together": {("indikator", "tahun")},
            },
        ),
    ]
