# Generated by Django 5.2.14 on 2026-06-04 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0041_move_data_capaian_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatuDataset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ckan_id", models.CharField(max_length=100, verbose_name="ID CKAN")),
                (
                    "name",
                    models.SlugField(
                        blank=True, default="", max_length=200, verbose_name="Slug"
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="Judul")),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                (
                    "organisasi",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Organisasi",
                    ),
                ),
                (
                    "lisensi",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Lisensi"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="Tag"
                    ),
                ),
                (
                    "jumlah_resource",
                    models.PositiveIntegerField(default=0, verbose_name="Jumlah file"),
                ),
                (
                    "metadata_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Diperbarui"
                    ),
                ),
                (
                    "portal_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=400,
                        verbose_name="Tautan portal",
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data mentah"
                    ),
                ),
                ("harvested_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dataset Satu Data",
                "verbose_name_plural": "Dataset Satu Data",
                "ordering": ["title", "id"],
            },
        ),
        migrations.CreateModel(
            name="SatuDataSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(max_length=300, verbose_name="Basis URL CKAN"),
                ),
                (
                    "nama_portal",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Nama portal",
                    ),
                ),
                (
                    "organisasi_filter",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Filter organisasi (opsional)",
                    ),
                ),
                (
                    "last_harvested",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terakhir di-harvest"
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Status terakhir",
                    ),
                ),
                (
                    "last_pesan",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Pesan terakhir",
                    ),
                ),
                (
                    "last_jumlah",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah dataset terakhir"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sumber Satu Data",
                "verbose_name_plural": "Sumber Satu Data",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SatuDataResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ckan_id",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="ID CKAN"
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        blank=True, default="", max_length=400, verbose_name="Nama file"
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Format"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=600,
                        verbose_name="Tautan unduh",
                    ),
                ),
                (
                    "ukuran",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Ukuran (byte)"
                    ),
                ),
                (
                    "last_modified",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Diperbarui"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Data mentah"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="geonode_project.satudataset",
                        verbose_name="Dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "File Satu Data",
                "verbose_name_plural": "File Satu Data",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="satudataset",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="datasets",
                to="geonode_project.satudatasource",
                verbose_name="Sumber",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="satudataset",
            unique_together={("source", "ckan_id")},
        ),
    ]
