# Generated by Django 5.2.14 on 2026-06-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0043_seed_integrasi_satudata_menu"),
    ]

    operations = [
        migrations.AddField(
            model_name="satudatasource",
            name="verifikasi_ssl",
            field=models.BooleanField(
                default=True,
                help_text="Nonaktifkan bila portal memakai sertifikat yang tak terverifikasi.",
                verbose_name="Verifikasi sertifikat SSL",
            ),
        ),
    ]
