# Generated by Django 5.2.14 on 2026-06-04 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0039_remove_modeltranslation"),
        ("geonode_project", "0044_satudatasource_verifikasi_ssl"),
    ]

    operations = [
        migrations.AddField(
            model_name="satudataresource",
            name="document",
            field=models.ForeignKey(
                blank=True,
                help_text="Terisi bila file ini sudah diunduh & didaftarkan sebagai Dokumen.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
                verbose_name="Dokumen GeoNode",
            ),
        ),
    ]
