# Generated by Django 5.2.14 on 2026-06-04 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0045_satudataresource_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="satudataset",
            name="walidata",
            field=models.ForeignKey(
                blank=True,
                help_text="Hasil pencocokan otomatis organisasi CKAN ke daftar Walidata.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="satu_datasets",
                to="geonode_project.walidata",
                verbose_name="Walidata",
            ),
        ),
    ]
