# Generated by Django 5.2.14 on 2026-06-05 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0039_remove_modeltranslation"),
        ("geonode_project", "0046_satudataset_walidata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentWalidata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walidata_link",
                        to="documents.document",
                        verbose_name="Dokumen",
                    ),
                ),
                (
                    "walidata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="geonode_project.walidata",
                        verbose_name="Walidata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Walidata Dokumen",
                "verbose_name_plural": "Walidata Dokumen",
            },
        ),
    ]
