# Generated by Django 5.2.14 on 2026-06-06 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0047_documentwalidata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatuDataOrgWalidata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_title",
                    models.CharField(max_length=200, verbose_name="Organisasi CKAN"),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_maps",
                        to="geonode_project.satudatasource",
                        verbose_name="Sumber",
                    ),
                ),
                (
                    "walidata",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="org_maps",
                        to="geonode_project.walidata",
                        verbose_name="Walidata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pemetaan Organisasi Walidata",
                "verbose_name_plural": "Pemetaan Organisasi Walidata",
                "ordering": ["org_title"],
                "unique_together": {("source", "org_title")},
            },
        ),
    ]
