# Generated by Django 5.2.14 on 2026-06-06 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0048_satudataorgwalidata"),
        ("layers", "0046_remove_modeltranslation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetWalidata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walidata_link",
                        to="layers.dataset",
                        verbose_name="Dataset",
                    ),
                ),
                (
                    "walidata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geo_datasets",
                        to="geonode_project.walidata",
                        verbose_name="Walidata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Walidata Dataset",
                "verbose_name_plural": "Walidata Dataset",
            },
        ),
    ]
