# Generated by Django 5.2.14 on 2026-06-06 23:50
import csv
import os

from django.db import migrations, models

CSV_PATH = os.path.join(
    os.path.dirname(__file__), "..", "seed_data", "kode_bps_kabkota.csv"
)


def seed_kode_bps(apps, schema_editor):
    """Isi crosswalk kabkota dari seed_data/kode_bps_kabkota.csv (idempotent)."""
    RefKodeBps = apps.get_model("geonode_project", "RefKodeBps")
    if not os.path.exists(CSV_PATH):
        return
    with open(CSV_PATH, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            pum = (r.get("kode_pum") or "").strip()
            bps = (r.get("kode_bps") or "").strip()
            if not pum or not bps:
                continue
            RefKodeBps.objects.update_or_create(
                level="kabkota", kode_pum=pum,
                defaults={
                    "kode_bps": bps,
                    "nama": (r.get("nama") or "").strip(),
                    "file_logo": (r.get("file_logo") or "").strip(),
                },
            )


def unseed_kode_bps(apps, schema_editor):
    RefKodeBps = apps.get_model("geonode_project", "RefKodeBps")
    RefKodeBps.objects.filter(level="kabkota").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0050_rename_data_spasial_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefKodeBps",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("provinsi", "Provinsi"),
                            ("kabkota", "Kabupaten/Kota"),
                            ("kecamatan", "Kecamatan"),
                            ("desa", "Desa/Kelurahan"),
                        ],
                        db_index=True,
                        default="kabkota",
                        max_length=16,
                        verbose_name="Jenjang",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "kode_bps",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Kode BPS"
                    ),
                ),
                (
                    "nama",
                    models.CharField(blank=True, max_length=255, verbose_name="Nama"),
                ),
                (
                    "file_logo",
                    models.CharField(
                        blank=True,
                        help_text="Berkas di seed_data/logo_kab/ (kab-h250px-<digit kode>.<ext>); kosong bila belum ada logo.",
                        max_length=255,
                        verbose_name="Nama berkas logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crosswalk Kode BPS",
                "verbose_name_plural": "Crosswalk Kode BPS",
                "ordering": ["level", "kode_pum"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("level", "kode_pum"), name="uniq_refkodebps_level_pum"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_kode_bps, unseed_kode_bps),
    ]
