# Generated by Django 5.2.14 on 2026-06-07 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0053_kode_bps_kecdesa"),
    ]

    operations = [
        migrations.CreateModel(
            name="FolurCapaianWilayah",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("desa", "Desa/Kelurahan"),
                            ("kecamatan", "Kecamatan"),
                        ],
                        db_index=True,
                        default="desa",
                        max_length=10,
                        verbose_name="Jenjang",
                    ),
                ),
                (
                    "kode_pum",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Kode PUM/Kemendagri"
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nama wilayah",
                    ),
                ),
                (
                    "tahun",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Tahun"
                    ),
                ),
                ("nilai", models.FloatField(verbose_name="Realisasi")),
                (
                    "catatan",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Catatan"
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "indikator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capaian_wilayah",
                        to="geonode_project.folurindikator",
                        verbose_name="Indikator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capaian FOLUR per Wilayah",
                "verbose_name_plural": "Capaian FOLUR per Wilayah",
                "ordering": ["indikator", "level", "kode_pum", "-tahun"],
                "indexes": [
                    models.Index(
                        fields=["indikator", "tahun", "level"],
                        name="geonode_pro_indikat_1a1b46_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indikator", "level", "kode_pum", "tahun"),
                        name="uniq_folurcapaianwilayah",
                    )
                ],
            },
        ),
    ]
