# Generated by Django 5.2.14 on 2026-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0054_folurcapaianwilayah"),
    ]

    operations = [
        migrations.AddField(
            model_name="folurcapaianwilayah",
            name="kegiatan",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jenis kegiatan di wilayah ini (teks bebas), mis. 'intensifikasi lahan tanaman padi'.",
                max_length=255,
                verbose_name="Kegiatan",
            ),
        ),
    ]
