# Generated by Django 5.2.14 on 2026-06-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0055_folurcapaianwilayah_kegiatan"),
    ]

    operations = [
        migrations.AddField(
            model_name="folurindikator",
            name="palet",
            field=models.CharField(
                choices=[
                    ("hijau", "Hijau (bawaan)"),
                    ("biru", "Biru"),
                    ("teal", "Teal / Toska"),
                    ("oranye", "Oranye"),
                    ("merah", "Merah"),
                    ("ungu", "Ungu"),
                    ("pelangi", "Pelangi (Spektral)"),
                    ("viridis", "Viridis"),
                    ("magma", "Magma"),
                ],
                default="hijau",
                help_text="Skema warna class interval di legenda & choropleth /webgis2/.",
                max_length=20,
                verbose_name="Palet warna peta",
            ),
        ),
    ]
