# Generated by Django 5.2.14 on 2026-06-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0056_folurindikator_palet"),
    ]

    operations = [
        migrations.AddField(
            model_name="folurindikator",
            name="agregasi",
            field=models.CharField(
                choices=[
                    ("tahunan", "Tahunan (snapshot per tahun)"),
                    ("kumulatif", "Kumulatif (jumlah antar tahun)"),
                ],
                default="tahunan",
                help_text="tahunan = nilai tahun terpilih; kumulatif = jumlah s.d. tahun terpilih (mis. CI3 Lahan terestorasi). Dipakai Sitroom, Capaian Publik, webgis2.",
                max_length=10,
                verbose_name="Agregasi antar-tahun",
            ),
        ),
    ]
