# Generated by Django 5.2.14 on 2026-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0057_folurindikator_agregasi"),
    ]

    operations = [
        migrations.AddField(
            model_name="folurindikator",
            name="sumber_agregat",
            field=models.CharField(
                choices=[
                    ("manual", "Manual (entri agregat per tahun)"),
                    ("roll_up", "Roll-up (Σ dari data per-wilayah)"),
                ],
                default="manual",
                help_text="manual = pakai entri Realisasi Tahunan (FolurCapaian); roll_up = hitung dari Σ Capaian per Wilayah (desa) → sinkron lintas yurisdiksi.",
                max_length=10,
                verbose_name="Sumber angka agregat",
            ),
        ),
    ]
