# Generated by Django 5.2.14 on 2026-06-08 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0058_folurindikator_sumber_agregat"),
    ]

    operations = [
        migrations.AddField(
            model_name="folurcapaianwilayah",
            name="komoditas",
            field=models.ForeignKey(
                blank=True,
                help_text="Relasi ke Fokus Komoditas (Pengaturan). Opsional.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capaian_wilayah",
                to="geonode_project.komoditasfokus",
                verbose_name="Komoditas fokus",
            ),
        ),
    ]
