# Generated by Django 5.2.15 on 2026-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geonode_project", "0061_seed_komoditas_gambar_terbaru"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteidentity",
            name="font_option",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Opsi 1"), (2, "Opsi 2"), (3, "Opsi 3")],
                default=1,
                help_text="1 dari 3 kombinasi font (serif/sans/mono) untuk tema aktif.",
                verbose_name="Kombinasi font",
            ),
        ),
    ]
